version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask-app:
    build:
      context: ./app      # path to your Flask Dockerfile
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db

volumes:
  mongo_data:
